[
    {
        "createdAt": "August 1st, 2022 at 7:45 am",
        "time": "8:00 pm",
        "title": "Back-to-school-party",
        "date": "August 31st, 2022",
        "commitments": ["pamwash123", "eholt2"],
        "flakes": [],
        "theme": "Beach",
        "active": true,
        "eventAuthor": "mlars2",
        "description": "This party is to celebrate everyone goinb back to school!",
        "address": "1245 N Cherry Blossom Lane, Tucson, Arizona, 78732",
        "private": false,
        "image": "",
        "recap": []
    },
    {
        "createdAt": "Sepetember 21st, 2021 at 8:20 pm",
        "time": "7:30 pm",
        "title": "Matthew Larson's Birthday Party",
        "date": "September 30th, 2021",
        "commitments": ["highvaluemale1"],
        "flakes": [],
        "theme": "Playboy",
        "active": false,
        "eventAuthor": "mlars2",
        "description": "Matthew Larson's 21st Birthday rager",
        "address": "6050 E 4th Street, Tucson, Arizona, 78732",
        "private": true,
        "image": "",
        "recap": []
    },
    {
        "createdAt": "July 3rd, 2022 at 3:00 pm",
        "time": "1:00 pm",
        "title": "July 4th America Celebration",
        "date": "July 4th, 2022",
        "commitments": ["pamwash123", "vtipei34"],
        "flakes": [],
        "theme": "Murica",
        "active": false,
        "eventAuthor": "ryrathb",
        "description": "Celebrating America's Freedom",
        "address": "345 N Lamar Boulevard, Austin, Texas, 78732",
        "private": false,
        "image": "",
        "recap": []
    },
    {
        "createdAt": "August 15th, 2022 at 4:00 pm",
        "time": "10:00 pm",
        "title": "High Value Halloween Party",
        "date": "October 31st, 2022",
        "commitments": ["mlars2", "robbiep6"],
        "flakes": [],
        "theme": "Spooky",
        "active": true,
        "eventAuthor": "highvauemale1",
        "description": "This as a halloween party where high value males get to dress up as other high value males",
        "address": "460 Congress Road, Tucson, Arizona, 85719",
        "private": false,
        "image": "",
        "recap": []
    },
    {
        "createdAt": "June 30th, 2022 at 7:00pm",
        "time": "12:00 pm",
        "title": "Stephen's Wedding",
        "date": "July 28th, 2022",
        "commitments": ["robbiep6", "maxcris"],
        "flakes": [],
        "theme": "Marriage",
        "active": false,
        "eventAuthor": "shein78",
        "description": "This is a marriage ceremony for Stephen Heinen and his betrothed",
        "address": "678 West Broadway Road, San Antonio, Texas, 76571",
        "private": true,
        "image": "",
        "recap": []
    },
    {
        "createdAt": "May 20th, 2022 at 2:30 pm",
        "time": "6:00",
        "title": "Book Club Party",
        "date": "September 12th, 2022",
        "commitments": ["eholt2"],
        "flakes": [],
        "theme": "Reading",
        "active": true,
        "eventAuthor": "bdavidson1",
        "description": "Let's get reading!",
        "address": "4589 W Awatuikee Road, Phoenix, Arizona, 85226",
        "private": false,
        "image": "",
        "recap": []
    },
    {
        "createdAt": "August 2nd, 2022 at 9:00 pm",
        "time": "3:00 pm",
        "title": "Jungle Day Party Get-Together",
        "date": "August 10th, 2022",
        "commitments": ["shein78"],
        "flakes": [],
        "theme": "Jungle",
        "active": false,
        "eventAuthor": "maxcris",
        "description": "Day party to enjoy the last days of summer",
        "address": "567 W Rosecrans Road, Los Angeles, California, 90210",
        "private": false,
        "image": "",
        "recap": []
    },
    {
        "createdAt": "August 26th, 2022 at 3:00 pm",
        "time": "4:00 pm",
        "title": "Dinner Party!!",
        "date": "August 31st, 2022",
        "commitments": ["pamwash123"],
        "flakes": [],
        "theme": "Great Gatsby",
        "active": true,
        "eventAuthor": "ctolnai4",
        "description": "1920's themed dinner party",
        "address": "712 N Phoenix Drive, Phoenix, Arizona, 85234",
        "private": true,
        "image": "",
        "recap": []
    },
]